name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */3 * * *" # Every 3 hours

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Install Playwright
        run: |
          uv run playwright install chromium --only-shell

      - name: Update
        run: |
          uv run python scrape.py
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
      
      - name: "[Debug] Show the contents of data/playwright_state.json.enc"
        run: |
          cat data/playwright_state.json.enc
      
      - name: Translate
        run: |
          uv run python translate.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Commit and push changes
        run: |
          git add data
          git restore --staged data/playwright_state.json.enc
          HAS_CHANGES=$(git diff --cached --exit-code > /dev/null && echo -n no || echo -n yes)
          if [ $HAS_CHANGES = "no" ]; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
          git add data
          git commit -m "Update data"
          git push
          git show HEAD -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: noreply
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: noreply